# Generated by Django 6.0.6 on 2026-07-04 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_house(apps, schema_editor):
    Chore = apps.get_model('core', 'Chore')
    for chore in Chore.objects.filter(house__isnull=True, room__isnull=False):
        chore.house_id = chore.room.house_id
        chore.save(update_fields=['house'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_chores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chore',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='core.house'),
        ),
        migrations.AddField(
            model_name='chore',
            name='recurrence_type',
            field=models.CharField(choices=[('floating', 'Every N days after last completed'), ('fixed', 'Every N days from a fixed start date')], default='floating', max_length=10),
        ),
        migrations.AddField(
            model_name='chore',
            name='start_date',
            field=models.DateField(blank=True, help_text="Anchor date for fixed-schedule recurrence (required when recurrence_type='fixed').", null=True),
        ),
        migrations.AddField(
            model_name='chore',
            name='task_type',
            field=models.CharField(choices=[('planned', 'Planned (assigned to a room, recurring)'), ('one_time', 'One time (ad hoc, not recurring)')], default='planned', max_length=10),
        ),
        migrations.AlterField(
            model_name='chore',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='The chore becomes due again this many days after it was last completed.', null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='core.room'),
        ),
        migrations.RunPython(backfill_house, migrations.RunPython.noop),
    ]
